
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 35
#define YY_END_OF_BUFFER 36
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[90] =
    {   0,
        0,    0,   36,   35,    2,    1,   35,    4,   35,   12,
       13,   20,   11,   35,   21,    9,   16,   10,   15,   31,
       28,   29,   31,   31,   31,   31,   31,    3,    1,   19,
        4,    0,   22,    0,   33,    0,    0,   21,   18,   14,
       17,   34,   31,    0,   31,   31,    5,   31,   31,    3,
        0,    0,    0,    0,   31,   31,   31,   31,   31,    0,
        0,    0,    0,   23,    0,    6,    7,   31,   31,    0,
        0,    0,   25,    0,   31,   31,    0,    0,   24,   32,
        0,   30,   31,    0,    0,    8,   26,   27,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    1,    6,    1,    1,    1,    7,    8,
        9,    1,   10,   11,    1,   12,    1,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   14,    1,   15,
       16,   17,    1,    1,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       19,   20,   21,    1,   18,    1,   22,   18,   18,   23,

       24,   25,   18,   18,   26,   18,   18,   27,   18,   28,
       18,   29,   18,   30,   31,   32,   33,   18,   18,   18,
       18,   18,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[34] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    1,    1,
        1,    1,    3,    1,    1,    1,    1,    4,    5,    1,
        1,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4
    } ;

static yyconst flex_int16_t yy_base[97] =
    {   0,
        0,   32,  171,  172,  172,  172,  154,    0,   28,  172,
      145,  172,  172,   15,  133,  172,  127,  126,  125,   30,
      172,  172,   31,   32,   35,   34,   37,   42,   61,  172,
        0,   50,  172,    0,  172,  110,  110,  124,  172,  172,
      172,  172,   39,  123,   54,   58,   59,   43,   49,   81,
       75,  105,  102,   73,   67,   65,   73,   74,   75,   96,
      108,  106,   55,  172,    0,   81,   83,   87,   91,  100,
       97,  102,  172,  118,  112,  116,   88,   78,  172,  172,
       84,  172,  121,   80,   64,  172,  172,  172,  172,  144,
      149,  152,  157,  162,   48,  165

    } ;

static yyconst flex_int16_t yy_def[97] =
    {   0,
       89,    1,   89,   89,   89,   89,   89,   90,   91,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   92,
       89,   89,   92,   92,   92,   92,   92,   89,   89,   89,
       90,   91,   89,   93,   89,   89,   89,   89,   89,   89,
       89,   89,   92,   89,   92,   92,   92,   46,   46,   89,
       94,   89,   89,   89,   46,   46,   46,   46,   46,   94,
       89,   89,   89,   89,   95,   46,   46,   46,   46,   89,
       89,   89,   89,   96,   92,   92,   89,   89,   89,   89,
       96,   89,   92,   89,   89,   89,   89,   89,    0,   89,
       89,   89,   89,   89,   89,   89

    } ;

static yyconst flex_int16_t yy_nxt[206] =
    {   0,
        4,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,    4,
       22,   20,   23,   24,   20,   25,   20,   20,   26,   27,
       20,   20,   20,   28,   33,   29,   36,   42,   42,   42,
       37,   42,   42,   50,   42,   50,   42,   34,   44,   44,
       44,   74,   44,   44,   45,   44,   33,   44,   46,   47,
       49,   42,   50,   48,   50,   42,   42,   72,   58,   34,
       65,   88,   44,   43,   43,   73,   44,   44,   55,   43,
       59,   33,   50,   56,   50,   54,   63,   87,   57,   66,
       43,   80,   43,   64,   34,   43,   67,   43,   43,   43,

       43,   68,   33,   43,   43,   43,   43,   69,   43,   85,
       84,   43,   43,   43,   72,   34,   43,   43,   75,   82,
       76,   43,   79,   42,   86,   80,   78,   77,   42,   71,
       44,   70,   62,   61,   44,   54,   38,   53,   52,   44,
       41,   40,   39,   83,   31,   38,   31,   31,   31,   32,
       32,   32,   32,   32,   43,   43,   43,   51,   35,   51,
       51,   51,   60,   60,   60,   60,   60,   81,   81,   30,
       89,    3,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,

       89,   89,   89,   89,   89
    } ;

static yyconst flex_int16_t yy_chk[206] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    9,    2,   14,   20,   23,   24,
       14,   26,   25,   28,   27,   28,   43,    9,   20,   23,
       24,   95,   26,   25,   23,   27,   32,   43,   24,   25,
       27,   45,   29,   26,   29,   46,   47,   63,   48,   32,
       55,   85,   45,   48,   49,   63,   46,   47,   45,   49,
       49,   51,   50,   46,   50,   54,   54,   84,   46,   56,
       56,   81,   55,   54,   51,   56,   57,   55,   57,   58,

       59,   58,   60,   57,   58,   59,   66,   59,   67,   78,
       77,   66,   68,   67,   72,   60,   69,   68,   68,   75,
       69,   69,   72,   76,   83,   74,   71,   70,   83,   62,
       75,   61,   53,   52,   76,   44,   38,   37,   36,   83,
       19,   18,   17,   76,   90,   15,   90,   90,   90,   91,
       91,   91,   91,   91,   92,   92,   92,   93,   11,   93,
       93,   93,   94,   94,   94,   94,   94,   96,   96,    7,
        3,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,

       89,   89,   89,   89,   89
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "checkdatatype.l"
#line 2 "checkdatatype.l"
  // usage format: clear && flex checkdatatype.l && g++ -std=c++11 lex.yy.c -o checkdatatype
  #include <vector>
  #include <iostream>
  #include <string>
  #include <map>
  #include <fstream>

  using namespace std;

  /* Debug Levels
   * 0 = Critical only
   * 1 = Informational
   * 2 = Verbose
   * 3 = input parsing
   */
  #define DEBUG 5
  // values to variable offset
  #define VAL2VAR 4
  #define MAINPROGRAM -1

  // testing only
  //extern int yylex();

  //
  // Structures
  //
  // Debug levels
  enum dbg { CRITICAL, INFO, VERBOSE, ALL };
  enum lex { NO_VAL = 0, ERROR, WARNING, 
            SPACE, LF, INDENT, FILE_EOF, COMMENT, 
            FUNC_DEC, FUNC_DEC_END, FUNC_CALL,
            AND, OR, NOT,
            COND_IF, COND_ELSE, LOOP_FOR, LOOP_WHILE, RETURN, NO_RETURN, COLON,
            C_EQUALS, C_GREATER, C_LESSER, C_GREATER_EQUALS, C_LESSER_EQUALS, C_NOT_EQUALS,
            COMMA, ASSIGN, PAREN_OP, PAREN_CL, TRAILING_PAREN,
            OP_ADD, MATH_SUB, MATH_DIV, MATH_MUL, MATH_EXP, MATH_MOD,
            VAL_BOOL, VAL_STRING, VAL_INT, VAL_FLOAT,
            LABEL, OTHER, PRINT,
            LIST_INDEX, LIST_SLICE_ONE_ARG, LIST_SLICE_TWO_ARG, LIST_DEC, LIST_DEC_END, LIST_APPEND, LIST_APPEND_END, LIST_INSERT, LIST_INSERT_END, LIST_RANGE };
  static const char* lex2str[] = { "NO_VAL", "ERROR", "WARNING",
      "SPACE", "LF", "INDENT", "FILE_EOF", "COMMENT",
      "FUNC_DEC", "FUNC_DEC_END", "FUNC_CALL",
      "AND", "OR", "NOT",
      "COND_IF", "COND_ELSE", "LOOP_FOR", "LOOP_WHILE", "RETURN", "NO_RETURN", "COLON",
      "C_EQUALS", "C_GREATER", "C_LESSER", "C_GREATER_EQUALS", "C_LESSER_EQUALS", "C_NOT_EQUALS",
      "COMMA", "ASSIGN", "PAREN_OP", "PAREN_CL", "TRAILING_PAREN",
      "OP_ADD", "MATH_SUB", "MATH_DIV", "MATH_MUL", "MATH_EXP", "MATH_MOD",
      "BOOL", "STRING", "INT", "FLOAT",
      "LABEL", "OTHER", "PRINT",
      "LIST_INDEX", "LIST_SLICE_ONE_ARG", "LIST_SLICE_TWO_ARG", "LIST_DEC", "LIST_DEC_END", "LIST_APPEND", "LIST_APPEND_END", "LIST_INSERT", "LIST_INSERT_END", "LIST_RANGE" };

  // Tokens
  typedef struct {
    int type; // variable type (list will only take the first instance type)
    string text; // variable name
    int line;    // line number
  } token;

  // latest variable values
  typedef struct {
    int type; // type of the variable
    string text;  // value of the variable
  } simple_var; //vector of simple_var access hash map -> identifier name -> take variable type

  // variable construct, can be simple or list
  typedef struct
  {
    bool is_list;
    simple_var simple;  // simple variable
    vector<simple_var> list; // list variable
  } variable;

  typedef struct {
    int start; // def starting line
    int end; // def ending line
    string text;
    int t_index; // function declaration location in global_token_list
    vector<variable> arg;
    map<string, vector<variable> > var_map;
  } function;

  // within a list flag
  bool in_list = false;
  // last label, used for input
  int input_last_label = 0;
  // input token list using FLEX
  vector<token> global_token_list;
  // function declaration flag
  bool func_decl = false;
  // list appending flag
  bool list_append = false;
  // list insert flag
  bool list_insert = false;
  // boolean to print a line or not
  vector<string> out_string;
  // integer for output line
  vector<string> err_string;
  vector<int> err_lines;

  // output file
  string out_file;
  ofstream out;

  // line number
  int py_line_num = 1;

  // handles token inputs
  void inputHandler(int type, string text)
  {
    token t;
    t.type = type;
    t.text = text;
    t.line = py_line_num;
    if(t.type == LF)
    {
      py_line_num++;
    }

    // if function definiton, remove "def "
    if(t.type == FUNC_DEC)
    {
      t.text = text.substr(4);
      func_decl = true;
    }
    // found a list append
    else if(t.type == LIST_APPEND)
    {
      list_append = true;
    }
    else if(t.type == LIST_INSERT)
    {
      list_insert = true;
    }

    // if function def occured before and we see "):"
    if(func_decl && t.type == FUNC_DEC_END)
    {
      func_decl = false;
    }
    // we probably encountered the end of a if/for/while statement
    else if(!func_decl && t.type == FUNC_DEC_END) 
    {
      t.type = PAREN_CL;
      t.text = ")";
      if(DEBUG >= 3) 
        cout << "Line " << t.line << ": (" << lex2str[t.type] << "): \"" << t.text << "\"\n";
      global_token_list.push_back(t);
      t.type = COLON;
      t.text = ":";
    }

    // check if we have a conditional statement and not a function call
    // i.e if( else(
    if(t.type == FUNC_CALL)
    {
      // not handling loops for this assignment
      if(t.text == "if(")
      {
        t.text = "if";
        t.type = COND_IF;
      }
      else if (t.text == "elif(")
      {
        t.text = "elif";
        t.type = COND_IF;
      }
      else if (t.text == "else(")
      {
        t.text = "else";
        t.type = COND_ELSE;
      }
      // remove last character
      if(t.type == COND_IF || t.type == COND_ELSE)
      {       
        if(DEBUG >= 3) 
          cout << "Line " << t.line << ": (" << lex2str[t.type] << "): \"" << t.text << "\"\n";
        global_token_list.push_back(t);
        t.type = PAREN_OP;
        t.text = "(";
      }
    }

    // check if any LABELs are a LIST
    if(t.type == LIST_DEC)
    {
      in_list = true;
      // last label is a LIST
      if(global_token_list[input_last_label].type == LABEL)
      {
        cout << "\tFound list label: (" << global_token_list[input_last_label].text << ")\n";
      }    
    }
    global_token_list.push_back(t);
    
    // temp save last label for list declarations
    if(t.type == LABEL)
    {
      input_last_label = global_token_list.size() - 1;
    }
    // end of list
    if(t.type == LIST_DEC_END)
      in_list = false;
    // Debug print
    if(DEBUG >= 3)
    {
      if(t.type != LF)
        cout << "Line " << t.line << ": (" << lex2str[t.type] << "): \"" << t.text << "\"\n";
      else
        cout << "Line " << t.line << ": (" << lex2str[t.type] << ")\n";
    }
  }
#line 740 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 215 "checkdatatype.l"

#line 927 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 90 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 172 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 216 "checkdatatype.l"
{ inputHandler(SPACE, yytext); }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 217 "checkdatatype.l"
{ inputHandler(LF, yytext); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 218 "checkdatatype.l"
{ inputHandler(INDENT, yytext); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 219 "checkdatatype.l"
{ inputHandler(COMMENT, yytext); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 220 "checkdatatype.l"
{ inputHandler(FILE_EOF, yytext); return 0; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 222 "checkdatatype.l"
{ inputHandler(COND_IF, yytext); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 223 "checkdatatype.l"
{ inputHandler(COND_IF, yytext); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 224 "checkdatatype.l"
{ inputHandler(COND_ELSE, yytext); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 225 "checkdatatype.l"
{ inputHandler(RETURN, yytext); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 226 "checkdatatype.l"
{ inputHandler(COLON, yytext); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 228 "checkdatatype.l"
{ inputHandler(ASSIGN, yytext); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 229 "checkdatatype.l"
{ inputHandler(COMMA, yytext); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 230 "checkdatatype.l"
{ inputHandler(PAREN_OP, yytext); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 231 "checkdatatype.l"
{ inputHandler(PAREN_CL, yytext); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 233 "checkdatatype.l"
{ inputHandler(C_EQUALS, yytext); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 234 "checkdatatype.l"
{ inputHandler(C_GREATER, yytext); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 235 "checkdatatype.l"
{ inputHandler(C_LESSER, yytext); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 236 "checkdatatype.l"
{ inputHandler(C_GREATER_EQUALS, yytext); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 237 "checkdatatype.l"
{ inputHandler(C_LESSER_EQUALS, yytext); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 238 "checkdatatype.l"
{ inputHandler(C_NOT_EQUALS, yytext); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 240 "checkdatatype.l"
{ inputHandler(OP_ADD, yytext); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 242 "checkdatatype.l"
{ inputHandler(VAL_INT, yytext); }
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 243 "checkdatatype.l"
{ inputHandler(VAL_STRING, yytext); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 245 "checkdatatype.l"
{ inputHandler(LIST_INDEX, yytext); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 246 "checkdatatype.l"
{ inputHandler(LIST_SLICE_TWO_ARG, yytext); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 247 "checkdatatype.l"
{ inputHandler(LIST_SLICE_ONE_ARG, yytext); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 248 "checkdatatype.l"
{ inputHandler(LIST_APPEND, yytext); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 249 "checkdatatype.l"
{ inputHandler(LIST_INSERT, yytext); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 250 "checkdatatype.l"
{ inputHandler(LIST_DEC, yytext); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 251 "checkdatatype.l"
{ inputHandler(LIST_DEC_END, yytext); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 254 "checkdatatype.l"
{ inputHandler(PRINT, yytext); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 255 "checkdatatype.l"
{ inputHandler(LABEL, yytext); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 257 "checkdatatype.l"
{ inputHandler(FUNC_DEC, yytext); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 258 "checkdatatype.l"
{ inputHandler(FUNC_DEC_END, yytext); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 259 "checkdatatype.l"
{ inputHandler(FUNC_CALL, yytext); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 261 "checkdatatype.l"
ECHO;
	YY_BREAK
#line 1192 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 90 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 90 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 89);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 261 "checkdatatype.l"


/* Temp storage for dead rules
[.*]+                         { inputHandler(OTHER, yytext); }
\"[^\"\\]*(\\.[^\"\\]*)*\"    { inputHandler(VAL_STRING, yytext); } "
[ ]                           { inputHandler(SPACE, yytext); }
*/

//////////////////////////////////////////////////////////////////////////////
// PRINT FUNCTIONS
//////////////////////////////////////////////////////////////////////////////
void printTokenList(vector<token> tokens, int tabs)
{
  if(DEBUG >= VERBOSE) {
    for(int i = 0; i < tokens.size(); i++)
    {
      for(int t = 0; t < tabs; t++)
        cout << "\t";
      cout << "Token " << tokens[i].text << " has a type of " << lex2str[tokens[i].type] << "\n";
    }
  }
}

void printVarList(vector<simple_var> list, int tabs)
{
  if(DEBUG >= VERBOSE) {
    for(int i = 0; i < list.size(); i++)
    {
      for(int t = 0; t < tabs; t++)
        cout << "\t";
      cout << "List element[" << to_string(i) << "] = " << list[i].text << " has a type of " << lex2str[list[i].type] << "\n";
    }
  }
}

//////////////////////////////////////////////////////////////////////////////
// UTILITY FUNCTIONS
//////////////////////////////////////////////////////////////////////////////
bool isCondition(token t)
{
  switch(t.type)
  {
    case C_EQUALS:
    case C_GREATER:
    case C_LESSER:
    case C_GREATER_EQUALS:
    case C_LESSER_EQUALS:
    case C_NOT_EQUALS:
      return true;
  };
  return false;
}

bool isError(token t)
{
  if(t.type == ERROR)
    return true;
  return false;
}

bool isLabel(token t)
{
  if(t.type == LABEL)
    return true;
  return false;
}

//////////////////////////////////////////////////////////////////////////////
// FUNCTION BUILDING AND CHECKING
//////////////////////////////////////////////////////////////////////////////
// checks if we're on a function line
// returns:
//   true for in a function
//   false for not in a function
// bool isFuncLine(int line, map<string, function> func_map)
// {
//   // for(map<string,function>::iterator i = func_map.begin(); i != func_map.end(); ++i)
//   // {
//   //   if(line >= i->second.start && line <= i->second.end)
//   //     return true;
//   // }
//   return false;
// }


// returns the lines for a function
// will include LF but not include LF followed by something non LF and non indented
// function getFuncLines(int i)
// {
//   function func;
//   func.start = global_token_list.at(i).line;
//   func.end = -1;
//   func.text = global_token_list.at(i).text;
//   func.t_index = i;
//   bool indent = true;

//   cout << "\nParsing function: " << global_token_list[i].text << "\n";
//   while(func.end == -1 and i < global_token_list.size())
//   {
//     // save variables
//     if(isLabel(global_token_list[i]))
//     {
//       list var = copyToken2Var(global_token_list[i]);
//       // save arguments
//       if(global_token_list[i].line == func.start)
//       {
//         func.arg.push_back(var);
//         //cout << "\tFound new argument: " << func.arg.back().text << ", type: " << lex2str[func.var_map[global_token_list[i].text].type] << "\n";
//       }
//       else if ( func.var_map.find(global_token_list[i].text) == func.var_map.end() ) 
//       {
//         func.var_map[global_token_list[i].text] = var;
//         //cout << "\tFound new variable: " << func.var_map[global_token_list[i].text].text << ", type: " << lex2str[func.var_map[global_token_list[i].text].type] << "\n";
//       }
//     }

//     // func calls end when there is a LF followed by any of the following (WITHOUT INDENT):
//     // FILE_EOF, FUNC_DEC, FUNC_CALL, VAR_CHAR, VAR_STRING, VAR_INT, VAR_FLOAT, LABEL, OTHER
//     switch(global_token_list[i].type)
//     {
//       case LF:
//         indent = false;
//         break;
//       case INDENT:
//         indent = true;
//         break;
//       case RETURN:
//         indent = true;
//         func.end = global_token_list[i].line;
//         break;
//       case FILE_EOF:
//       case FUNC_DEC:
//       case FUNC_CALL:
//       case VAL_STRING:
//       case VAL_INT:
//       case VAL_FLOAT:
//       case LABEL:
//       case OTHER:
//         if(!indent)
//           func.end = global_token_list[i].line - 1;
//         break;
//       default:
//         // do nothing
//         break;
//     };
//     i++;
//   }

//   return func;
// }

// Builds a map of functions
// map<string, function> pyBuildFunctions()
// {
//   map<string, function> func_map;
//   function func;
//   // find all function lines
//   // for(int i = 0; i < global_token_list.size(); i++)
//   // {
//   //   // save function lines
//   //   if(global_token_list.at(i).type == FUNC_DEC)
//   //   {
//   //     func = getFuncLines(i);
//   //     if(DEBUG >= ALL)
//   //       cout << "FUNCTION FOUND: " << func.text << " at lines(" << func.start << ", " << func.end << ") with t_index of " << func.t_index << "\n";
//   //     func_map[func.text] = func;
//   //   }
//   // }
//   return func_map;
// }

//////////////////////////////////////////////////////////////////////////////
// EVALUATING EXPRESSIONS/EQUATIONS
//////////////////////////////////////////////////////////////////////////////
// appends sub to the end of master
variable appendListToList( int start_index, int stop_index, variable sub, variable master)
{
  // add a 1 to include the final index for sub full length calls
  if(stop_index < sub.list.size())
    stop_index++;
  for(int i = start_index; i < stop_index; i++)
    master.list.push_back(sub.list[i]);
  return master;
}

// the string must contain a []
// returns a list name
string getLabelFromListIndex(string list_index_full)
{
  return list_index_full.substr(0, list_index_full.find('['));
}

// the string must contain a []
// returns the integer index
int getIndexFromListIndex(string list_index_full)
{
  string str_index = "";
  int i = 0;
  bool index_start = false;
  while(i < list_index_full.length())
  {
    if(list_index_full.at(i) == '[')
      index_start = true;
    else if(index_start && list_index_full.at(i) != ']')
      str_index = str_index + list_index_full.at(i);
    else
      index_start = false;
    i++;
  }
  if(str_index == "")
    return -1;
  else
    return stoi(str_index);
}

int getStartIndexFromSlice(string list_index_full)
{
  string str_index = "";
  int i = 0;
  bool index_start = false;
  while(i < list_index_full.length())
  {
    if(list_index_full.at(i) == '[')
      index_start = true;
    else if(index_start && list_index_full.at(i) != ':')
      str_index = str_index + list_index_full.at(i);
    else
      index_start = false;
    i++;
  }
  if(str_index == "")
    return -1;
  else
    return stoi(str_index);
}

int getEndIndexFromSlice(string list_index_full)
{
  string str_index = "";
  int i = 0;
  bool index_start = false;
  while(i < list_index_full.length())
  {
    if(list_index_full.at(i) == ':')
      index_start = true;
    else if(index_start && list_index_full.at(i) != ']')
      str_index = str_index + list_index_full.at(i);
    else
      index_start = false;
    i++;
  }
  if(str_index == "")
    return -1;
  else
    return stoi(str_index);
}

simple_var getIndexValue(string list_index, map<string, variable> var_map)
{
  string name = getLabelFromListIndex(list_index);
  int index = getIndexFromListIndex(list_index);
  cout << "getIndexValue: " << name << "[" << to_string(index) << "] = ";
  cout << var_map[name].list[index].text << "\n";
  return var_map[name].list[index];
}

// evaluates an "equation" - anything with variables or types is evaluated here
// returns a token:
//   token.text - text of evaluated equation
//   token.type - int type of evaluated equation (NO_VAL default, ERROR for issues )
//   token.line - line number of evaluated equation
map<string, variable> evalLine(int state, int index_t, vector<token> expr, map<string, variable> var_map)
{
  string var_name = "";
  variable var;
  int var_index = 0;
  int i = 0;
  // left hand side and operator
  token LHS, OP;

  // loop through expression
  while(i < expr.size())
  {
    // STEP1: look for a label first
    if(state == NO_VAL && expr[i].type == LABEL)
    {
      var_name = expr[i].text;
      state = LABEL;
    }
    else if(state == NO_VAL && expr[i].type == LIST_INDEX)
    {
      var_name = getLabelFromListIndex(expr[i].text);
      state = LABEL;
    }
    // STEP2: look for an assignment after
    else if(state == LABEL && expr[i].type == ASSIGN)
    {
      state = ASSIGN;
    }
    // STEP2: append
    // STEP2: remove
    // STEP3: assignment stuff
    else if(state == ASSIGN)
    {
      if(expr[i].type == VAL_INT || expr[i].type == VAL_STRING)
      {
        simple_var temp_var;
        temp_var.type == expr[i].type;
        temp_var.text = expr[i].text;
        var.list.push_back(temp_var);
      }
      else if(expr[i].type == LIST_DEC)
      {
        i++;
        while(i < expr.size() && (expr[i].type == VAL_INT || expr[i].type == VAL_STRING || expr[i].type == LABEL || expr[i].type == LIST_INDEX || expr[i].type == COMMA))
        {
          simple_var temp_var;
          switch(expr[i].type)
          {
            case COMMA:
              // do nothing with commas
              break;
            case VAL_INT:
            case VAL_STRING:
              temp_var.type = expr[i].type;
              temp_var.text = expr[i].text;
              var.list.push_back(temp_var);
              // cout << "VAL_INT_STRING push: " + temp_var.text << "\n";
              break;
            case LABEL:
              // simple variable (non-list) assume the map is correct
              temp_var.type = var_map[expr[i].text].simple.type;
              temp_var.text = var_map[expr[i].text].simple.text;
              var.list.push_back(temp_var);
              // cout << "LABEL push: " + temp_var.text << "\n";
              break;
            case LIST_INDEX:
              // item at index
              temp_var = getIndexValue(expr[i].text, var_map);
              var.list.push_back(temp_var);
              // cout << "LIST_INDEX push: " + temp_var.text << "\n";
              break;
            default:
              cout << "Unsupported or bad type: " << expr[i].text << ", type = " << lex2str[expr[i].type] << "\n";
          };
          i++;
        } // end while for list assignment
      }
      else if(expr[i].type == LABEL)
      {
        cout << "LABEL append: " << expr[i].text << "\n";
        printVarList(var_map[expr[i].text].list, 1);
        var = appendListToList(0, var_map[expr[i].text].list.size(), var_map[expr[i].text], var);
      }
      else if(expr[i].type == LIST_SLICE_ONE_ARG)
      {
        string name = getLabelFromListIndex(expr[i].text);
        int start_index = getStartIndexFromSlice(expr[i].text);
        // cout << "LIST_SLICE_ONE_ARG append: " << name << "\n";
        // cout << "Start/End Index: " << start_index << "\n";
        var = appendListToList(start_index, var_map[name].list.size(), var_map[name], var);
      }
      else if(expr[i].type == LIST_SLICE_TWO_ARG)
      {
        string name = getLabelFromListIndex(expr[i].text);
        int start_index = getStartIndexFromSlice(expr[i].text);
        int end_index = getEndIndexFromSlice(expr[i].text);
        // cout << "LIST_SLICE_TWO_ARG append: " << name << "\n";
        // cout << "Start/End Index: " << start_index << ", " << end_index << "\n";
        var = appendListToList(start_index, end_index, var_map[name], var);
      }
    } // end if(state == ASSIGN)
    i++;
  } // END EXPR while

  // value changed
  if(state == ASSIGN)
  {
    // is a list
    if(var.is_list)
    {
      cout << "State: " << lex2str[state] << "\n";
      cout << "List variable (" + var_name + ") value changed\n";
      printVarList(var.list, 1);
    }
    // is not a list
    else
      cout << "Simple variable changed: " << var_name << " = " << var.simple.text << "\n";
    var_map[var_name] = var;
  }
  // return the map - changed or unchanged
  return var_map;
}


//////////////////////////////////////////////////////////////////////////////
// BUILDING AN EQUATION/EXPRESSION
//////////////////////////////////////////////////////////////////////////////
// build an equation, returns when a LF, EOF, or FUNC_CALL are encountered
int buildLine(int line, int t_index, vector<token> t_list, vector<token>* expr)
{
  for(int i = t_index; i < t_list.size(); i++)
  {
    // push back things on the same line
    if(t_list[i].line == line)
    {
      if(t_list[i].type != LF)
        expr->push_back(t_list[i]);
    }
    // we're done
    else
      return expr->size();
  }
  return expr->size();
}


//////////////////////////////////////////////////////////////////////////////
// PRINT()
//////////////////////////////////////////////////////////////////////////////
//string -> identifier 
//variable -> type
//function -> output print out element inside the list
//slide , index , print all list operations print
//content 
//t_list (token)
//keep going through t_list -> look for var_map 
void printHandler(vector<token> t_list, map<string, variable> var_map)
{
  int i = 0;
  bool start_printing = false;
  // loop through token list
  while(i < t_list.size())
  {
    // check if there is a print statement
    if(t_list[i].type == PRINT)
    {
      start_printing = true;
    }
    // start printing
    if(start_printing && t_list[i].type != EOF)
    {
      //single index
      //slice 
      //the entire list
      //concanation 
      //double check for parenthesis 
      //printing out token type
      out << "Print looping through tokens: " << t_list[i].text << " of type "<< lex2str[t_list[i].type] << "\n";
      cout << "Print looping through tokens: " << t_list[i].text << " of type "<< lex2str[t_list[i].type] << "\n";
    }
    i++;
  }
}
//if else 
//////////////////////////////////////////////////////////////////////////////
// PARSER FOR MAIN PROGRAM
//////////////////////////////////////////////////////////////////////////////
// parse main body line by line
void pyCodeParser(vector<token> t_list, map<string, function> func_map)
{
  map<string, variable> var_map;
  int i = 0;
  int on_line = 0;
  // read all tokens and build expressions for each line
  while(i < t_list.size())
  {
    // skip function lines
    if(!isFuncLine(t_list[i].line, func_map))
    {
      // evaluate this line
      if(on_line != t_list[i].line)
      {
        vector<token> line_expr;
        int expr_size = buildLine(t_list[i].line, i, t_list, &line_expr);
        on_line = t_list[i].line;
        // evaluate the expression
        if(expr_size > 0)
        {
          cout << "Expression received:\n";
          printTokenList(line_expr, 1);
          var_map = evalLine(NO_VAL, 0, line_expr, var_map);
          // call print on every iteration cause why not
          out.open(out_file.c_str());
          printHandler(line_expr, var_map);
          out.close();
        }
        else
        {
          cout << "No expression on this line\n";
        }
      }
    }
    i++;
  }
}


//////////////////////////////////////////////////////////////////////////////
// MAIN
//////////////////////////////////////////////////////////////////////////////
int main(int argc, char** argv)
{
  map<string, function> func_map;
  vector<token> t_list;
  string in_file;

  cout << "You entered: " << argc << " arguments\n";
  if(argc != 2)
  {
    cout << "ERR: No program arguments (0), please restart in the format: ./checkdatatype file=program1.py\n";
    return 1;
  }

  // set up input/output files
  in_file = argv[1];
  size_t pos = in_file.find("file=");
  if(pos != 0)
  {
    cout << "ERR: Invalid program arguments (1), please restart in the format: checkdatatype file=program1.py\n";
    return 1;
  }
  in_file.erase(pos, 5);
  out_file = in_file;
  cout << "File " << in_file << " specified as input file\n";
  pos = out_file.find(".py");
  if(pos <= 0)
  {
    cout << "ERR: Invalid program arguments (2), please restart in the format: checkdatatype file=program1.py\n";
    return 1;
  }
  out_file.erase(pos, 3);
  out_file += ".out";
  cout << "File " << out_file << " set as output file\n";
  remove(out_file.c_str());

  // read input file
  FILE *py_file = fopen(in_file.c_str(), "r");
  if(!py_file) {
    cout << "ERR: Error opening file, maybe it doesnt exist?\n";
    return 1;
  }

  cout << "Input file Opened\n";
  yyin = py_file;

  // lex through the input
  while(yylex());
  t_list = global_token_list;
  // evaluate the call stack for all VAR types on
  // the LHS of the assign (where the RHS is constant)
  func_map = pyBuildFunctions();

  // evaluate the call stack for all VAR types on the
  // LHS of the assign (where the RHS is not a constant)
  pyCodeParser(t_list, func_map);
}
